# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&pinGlobalTxToPhysicalConnection=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true

server:
  port: 8066
logging:
  level:
    com.lty.threadpool.sys.mapper: debug

